apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if not .Values.namespaced }}Cluster{{ end }}RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ include "nauth.name" . }}
  name: manager-rolebinding
  {{- if .Values.namespaced }}
  namespace: {{ include "nauth.namespaceName" . }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if not .Values.namespaced }}Cluster{{ end }}Role
  name: manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "nauth.serviceAccountName" . }}
    namespace: {{ include "nauth.namespaceName" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if not .Values.namespaced }}Cluster{{ end }}RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ include "nauth.name" . }}
  name: manager-secret-rolebinding
  {{- if .Values.namespaced }}
  namespace: {{ include "nauth.namespaceName" . }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if not .Values.namespaced }}Cluster{{ end }}Role
  name: manager-secret-role
subjects:
  - kind: ServiceAccount
    name: {{ include "nauth.serviceAccountName" . }}
    namespace: {{ include "nauth.namespaceName" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ include "nauth.name" . }}
  name: leader-election-rolebinding
  namespace: {{ include "nauth.namespaceName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "nauth.serviceAccountName" . }}
  namespace: {{ include "nauth.namespaceName" . }}
