{{- if .Values.monitoring.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if not .Values.namespaced }}Cluster{{ end }}Role
metadata:
  name: {{ include "nauth.fullname" . }}-metrics-auth
  {{- if .Values.namespaced }}
  namespace: {{ include "nauth.namespaceName" . }}
  {{- end }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if not .Values.namespaced }}Cluster{{ end }}Role
metadata:
  name: {{ include "nauth.fullname" . }}-metrics-reader
  {{- if .Values.namespaced }}
  namespace: {{ include "nauth.namespaceName" . }}
  {{- end }}
rules:
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if not .Values.namespaced }}Cluster{{ end }}RoleBinding
metadata:
  name: {{ include "nauth.fullname" . }}-metrics-auth
  {{- if .Values.namespaced }}
  namespace: {{ include "nauth.namespaceName" . }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if not .Values.namespaced }}Cluster{{ end }}Role
  name: {{ include "nauth.fullname" . }}-metrics-auth
subjects:
- kind: ServiceAccount
  name: {{ include "nauth.serviceAccountName" . }}
  namespace: {{ include "nauth.namespaceName" . }}
{{- end }}
