apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if not .Values.namespaced }}Cluster{{ end }}RoleBinding
metadata:
  name: {{ include "nauth.fullname" . }}-manager
  labels:
    {{- include "nauth.labels" . | nindent 4 }}
  {{- if .Values.namespaced }}
  namespace: {{ include "nauth.namespaceName" . }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if not .Values.namespaced }}Cluster{{ end }}Role
  name: {{ include "nauth.fullname" . }}-manager
subjects:
  - kind: ServiceAccount
    name: {{ include "nauth.serviceAccountName" . }}
    namespace: {{ include "nauth.namespaceName" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if not .Values.namespaced }}Cluster{{ end }}RoleBinding
metadata:
  name: {{ include "nauth.fullname" . }}-manager-secret
  labels:
    {{- include "nauth.labels" . | nindent 4 }}
  {{- if .Values.namespaced }}
  namespace: {{ include "nauth.namespaceName" . }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if not .Values.namespaced }}Cluster{{ end }}Role
  name: {{ include "nauth.fullname" . }}-manager-secret
subjects:
  - kind: ServiceAccount
    name: {{ include "nauth.serviceAccountName" . }}
    namespace: {{ include "nauth.namespaceName" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nauth.fullname" . }}-leader-election
  labels:
    {{- include "nauth.labels" . | nindent 4 }}
  namespace: {{ include "nauth.namespaceName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "nauth.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "nauth.serviceAccountName" . }}
  namespace: {{ include "nauth.namespaceName" . }}
